export const FETCH_DATA_START = "FETCH_DATA_START";
export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
export const FETCH_DATA_FAILURE = "FETCH_DATA_FAILURE";
export const SET_SEARCH_TERM = "SET_SEARCH_TERM";
export const SET_SEARCH_RESULTS = "SET_SEARCH_RESULTS";
